name = "DynamicalSystemsToolkit"
uuid = "8423a06f-07d4-4e6e-9987-27f126ffa828"
authors = ["David AW Barton"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
RuntimeGeneratedFunctions = "7e49a35a-f44a-4d26-94aa-eba1b4ca6b47"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
RuntimeGeneratedFunctions = "0.5"
ModelingToolkit = "5.17"
StaticArrays = "1.2"
DocStringExtensions = "0.8"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
